# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2022-06-14T12:18:03+00:00

from __future__ import annotations
from datetime import datetime
from pydantic.dataclasses import dataclass
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import Extra, Field


@dataclass
class Model:
    pass


@dataclass
class VersionStatus:
    _type: Optional[str] = None


class Type(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Description:
    _type: Optional[Type] = None


class Type1(Enum):
    PARTY_SELF = "PARTY_SELF"
    PARTY_IDENTIFIED = "PARTY_IDENTIFIED"
    PARTY_RELATED = "PARTY_RELATED"


@dataclass
class Committer:
    _type: Type1


@dataclass
class TerminologyId:
    class Config:
        extra = Extra.forbid

    value: str
    _type: Optional[str] = None


class Type2(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class EhrAccess:
    _type: Optional[Type2] = None


class Type3(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class EhrStatus:
    _type: Optional[Type3] = None


class Type4(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class Directory:
    _type: Optional[Type4] = None


class Type5(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class Folder:
    _type: Optional[Type5] = None


class Type6(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class Composition:
    _type: Optional[Type6] = None


class Type7(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class Contribution:
    _type: Optional[Type7] = None


class Type8(Enum):
    ATTESTATION = "ATTESTATION"
    AUDIT_DETAILS = "AUDIT_DETAILS"


@dataclass
class Audit:
    _type: Optional[Type8] = None


@dataclass
class ArchetypeHrid:
    class Config:
        extra = Extra.forbid

    namespace: str
    rm_publisher: str
    rm_package: str
    rm_class: str
    concept_id: str
    release_version: str
    version_status: VersionStatus
    build_count: str
    _type: Optional[str] = None


class Type9(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid:
    _type: Type9


class Type10(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name:
    _type: Optional[Type10] = None


class Type11(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class Details:
    _type: Type11


class Type12(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Function:
    _type: Optional[Type12] = None


class Type13(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid1:
    _type: Type13


class Type14(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name1:
    _type: Optional[Type14] = None


class Type15(Enum):
    CLUSTER = "CLUSTER"
    ELEMENT = "ELEMENT"


@dataclass
class Item:
    _type: Type15


@dataclass
class IsoOid:
    class Config:
        extra = Extra.forbid

    value: str
    _type: Optional[str] = None


class Type16(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid2:
    _type: Type16


class Type17(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name2:
    _type: Optional[Type17] = None


class Type18(Enum):
    EXTRACT_FOLDER = "EXTRACT_FOLDER"
    GENERIC_CONTENT_ITEM = "GENERIC_CONTENT_ITEM"
    OPENEHR_CONTENT_ITEM = "OPENEHR_CONTENT_ITEM"


@dataclass
class Item1:
    _type: Type18


class Type19(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid3:
    _type: Type19


class Type20(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name3:
    _type: Optional[Type20] = None


class Type21(Enum):
    PARTY_SELF = "PARTY_SELF"
    PARTY_IDENTIFIED = "PARTY_IDENTIFIED"
    PARTY_RELATED = "PARTY_RELATED"


@dataclass
class Subject:
    _type: Type21


class Type22(Enum):
    PARTY_SELF = "PARTY_SELF"
    PARTY_IDENTIFIED = "PARTY_IDENTIFIED"
    PARTY_RELATED = "PARTY_RELATED"


@dataclass
class Provider:
    _type: Type22


class Type23(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class WorkflowId:
    _type: Optional[Type23] = None


class Type24(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class Protocol:
    _type: Type24


class Type25(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class GuidelineId:
    _type: Optional[Type25] = None


class Type26(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Narrative:
    _type: Optional[Type26] = None


class Type27(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid4:
    _type: Type27


class Type28(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name4:
    _type: Optional[Type28] = None


class Type29(Enum):
    EXTRACT_FOLDER = "EXTRACT_FOLDER"
    GENERIC_CONTENT_ITEM = "GENERIC_CONTENT_ITEM"
    OPENEHR_CONTENT_ITEM = "OPENEHR_CONTENT_ITEM"


@dataclass
class Item2:
    _type: Type29


class Type30(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid5:
    _type: Type30


class Type31(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name5:
    _type: Optional[Type31] = None


class Type32(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class Details1:
    _type: Type32


class Type33(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Language:
    _type: Optional[Type33] = None


@dataclass
class GenericId:
    class Config:
        extra = Extra.forbid

    value: str
    scheme: str
    _type: Optional[str] = None


class Type34(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid6:
    _type: Type34


class Type35(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name6:
    _type: Optional[Type35] = None


class Type36(Enum):
    PARTY_SELF = "PARTY_SELF"
    PARTY_IDENTIFIED = "PARTY_IDENTIFIED"
    PARTY_RELATED = "PARTY_RELATED"


@dataclass
class Subject1:
    _type: Type36


class Type37(Enum):
    PARTY_SELF = "PARTY_SELF"
    PARTY_IDENTIFIED = "PARTY_IDENTIFIED"
    PARTY_RELATED = "PARTY_RELATED"


@dataclass
class Provider1:
    _type: Type37


class Type38(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class WorkflowId1:
    _type: Optional[Type38] = None


class Type39(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class Protocol1:
    _type: Type39


class Type40(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class GuidelineId1:
    _type: Optional[Type40] = None


class Type41(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class Data:
    _type: Type41


class Type42(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid7:
    _type: Type42


class Type43(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name7:
    _type: Optional[Type43] = None


class Type44(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class Credentials:
    _type: Type44


@dataclass
class Iso8601Type:
    class Config:
        extra = Extra.forbid

    value: Optional[str] = None
    _type: Optional[str] = None


class Type45(Enum):
    ATTESTATION = "ATTESTATION"
    AUDIT_DETAILS = "AUDIT_DETAILS"


@dataclass
class Audit1:
    _type: Optional[Type45] = None


class Type46(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class Version:
    _type: Optional[Type46] = None


class Type47(Enum):
    PARTY_RELATED = "PARTY_RELATED"
    PARTY_IDENTIFIED = "PARTY_IDENTIFIED"


@dataclass
class Location:
    _type: Optional[Type47] = None


class Type48(Enum):
    PARTY_RELATED = "PARTY_RELATED"
    PARTY_IDENTIFIED = "PARTY_IDENTIFIED"


@dataclass
class Provider2:
    _type: Optional[Type48] = None


class Type49(Enum):
    PARTY_SELF = "PARTY_SELF"
    PARTY_IDENTIFIED = "PARTY_IDENTIFIED"
    PARTY_RELATED = "PARTY_RELATED"


@dataclass
class Subject2:
    _type: Type49


class Type50(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class OtherDetails:
    _type: Type50


class Type51(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class Contribution2:
    _type: Optional[Type51] = None


class Type52(Enum):
    ATTESTATION = "ATTESTATION"
    AUDIT_DETAILS = "AUDIT_DETAILS"


@dataclass
class CommitAudit:
    _type: Optional[Type52] = None


class Type53(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid8:
    _type: Type53


class Type54(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name8:
    _type: Optional[Type54] = None


class Type55(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class State:
    _type: Type55


class Type56(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class Data1:
    _type: Type56


@dataclass
class CodePhrase:
    class Config:
        extra = Extra.forbid

    terminology_id: TerminologyId
    code_string: str
    preferred_term: Optional[str] = None
    _type: Optional[str] = None


class Type57(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class WfDetails:
    _type: Type57


class Type58(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class OwnerId:
    _type: Optional[Type58] = None


class Type59(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name9:
    _type: Optional[Type59] = None


class Type60(Enum):
    DV_PARSABLE = "DV_PARSABLE"
    DV_MULTIMEDIA = "DV_MULTIMEDIA"


@dataclass
class OriginalContent:
    _type: Type60


class Type61(Enum):
    PARTY_RELATED = "PARTY_RELATED"
    PARTY_IDENTIFIED = "PARTY_IDENTIFIED"


@dataclass
class HealthCareFacility:
    _type: Optional[Type61] = None


class Type62(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class OtherContext:
    _type: Type62


class Type63(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid9:
    _type: Type63


class Type64(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name10:
    _type: Optional[Type64] = None


@dataclass
class Set:
    _type: Optional[str] = None


class Type65(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class OwnerId1:
    _type: Optional[Type65] = None


class Type66(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class OwnerId2:
    _type: Optional[Type66] = None


@dataclass
class Uri:
    _type: Optional[str] = None


class Type67(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid10:
    _type: Type67


class Type68(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name11:
    _type: Optional[Type68] = None


@dataclass
class TerminologyCode:
    class Config:
        extra = Extra.forbid

    terminology_id: str
    code_string: str
    uri: Uri
    terminology_version: Optional[str] = None
    _type: Optional[str] = None


class Type69(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid11:
    _type: Type69


class Type70(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name12:
    _type: Optional[Type70] = None


class Type71(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class Details2:
    _type: Type71


class Type72(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid12:
    _type: Type72


class Type73(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name13:
    _type: Optional[Type73] = None


class Type74(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class Details3:
    _type: Type74


class Type75(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Language1:
    _type: Optional[Type75] = None


@dataclass
class InternetId:
    class Config:
        extra = Extra.forbid

    value: str
    _type: Optional[str] = None


class Type76(Enum):
    PARTY_SELF = "PARTY_SELF"
    PARTY_IDENTIFIED = "PARTY_IDENTIFIED"
    PARTY_RELATED = "PARTY_RELATED"


@dataclass
class Author:
    _type: Type76


class Type77(Enum):
    ATTESTATION = "ATTESTATION"
    AUDIT_DETAILS = "AUDIT_DETAILS"


@dataclass
class Audit2:
    _type: Optional[Type77] = None


class Type78(Enum):
    SYNC_EXTRACT = "SYNC_EXTRACT"
    SYNC_EXTRACT_REQUEST = "SYNC_EXTRACT_REQUEST"


@dataclass
class Content:
    _type: Type78


@dataclass
class Message:
    class Config:
        extra = Extra.forbid

    author: Author
    audit: Audit2
    content: Content
    signature: Optional[str] = None
    _type: Optional[str] = None


class Type79(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid13:
    _type: Type79


class Type80(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name14:
    _type: Optional[Type80] = None


class Type81(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class Details4:
    _type: Type81


class Type82(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Language2:
    _type: Optional[Type82] = None


class Type83(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class ItemListItem:
    _type: Optional[Type83] = None


@dataclass
class ExtractEntityManifest:
    class Config:
        extra = Extra.forbid

    extract_id_key: str
    ehr_id: Optional[str] = None
    subject_id: Optional[str] = None
    other_ids: Optional[List[str]] = None
    item_list: Optional[List[ItemListItem]] = None
    _type: Optional[str] = None


@dataclass
class Interval:
    class Config:
        extra = Extra.forbid

    lower_unbounded: bool
    upper_unbounded: bool
    lower_included: bool
    upper_included: bool
    lower: Optional[Dict[str, Any]] = None
    upper: Optional[Dict[str, Any]] = None
    _type: Optional[str] = None


class Type84(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name15:
    _type: Optional[Type84] = None


class Type85(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class RequestId:
    _type: Optional[Type85] = None


class Type86(Enum):
    DV_EHR_URI = "DV_EHR_URI"
    DV_URI = "DV_URI"


@dataclass
class Uri1:
    _type: Optional[Type86] = None


@dataclass
class DVMultimedia:
    class Config:
        extra = Extra.forbid

    media_type: CodePhrase
    size: int
    charset: Optional[CodePhrase] = None
    language: Optional[CodePhrase] = None
    alternate_text: Optional[str] = None
    uri: Optional[Uri1] = None
    data: Optional[str] = None
    compression_algorithm: Optional[CodePhrase] = None
    integrity_check: Optional[str] = None
    integrity_check_algorithm: Optional[CodePhrase] = None
    thumbnail: Optional[DVMultimedia] = None
    _type: Optional[str] = None


class Type87(Enum):
    ATTESTATION = "ATTESTATION"
    AUDIT_DETAILS = "AUDIT_DETAILS"


@dataclass
class Audit3:
    _type: Optional[Type87] = None


@dataclass
class Version1:
    pass


class Type88(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class OwnerId3:
    _type: Optional[Type88] = None


@dataclass
class VersionTreeId:
    class Config:
        extra = Extra.forbid

    value: str
    _type: Optional[str] = None


class Type89(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Item3:
    _type: Optional[Type89] = None


@dataclass
class DVParagraph:
    class Config:
        extra = Extra.forbid

    items: List[Item3]
    _type: Optional[str] = None


class Type90(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Meaning:
    _type: Optional[Type90] = None


class Type91(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid14:
    _type: Type91


class Type92(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name16:
    _type: Optional[Type92] = None


class Type93(Enum):
    CLUSTER = "CLUSTER"
    ELEMENT = "ELEMENT"


@dataclass
class Item4:
    _type: Type93


class Type94(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid15:
    _type: Type94


class Type95(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name17:
    _type: Optional[Type95] = None


@dataclass
class Value:
    pass


class Type96(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class NullReason:
    _type: Optional[Type96] = None


class Type97(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class OtherDetails1:
    _type: Type97


class Type98(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid16:
    _type: Type98


class Type99(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name18:
    _type: Optional[Type99] = None


@dataclass
class Duration:
    class Config:
        extra = Extra.forbid

    value: Optional[str] = None
    _type: Optional[str] = None


class Type100(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid17:
    _type: Type100


class Type101(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name19:
    _type: Optional[Type101] = None


class Type102(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class Summary:
    _type: Type102


@dataclass
class Event:
    pass


class Type103(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid18:
    _type: Type103


class Type104(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name20:
    _type: Optional[Type104] = None


class Type105(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid19:
    _type: Type105


class Type106(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name21:
    _type: Optional[Type106] = None


@dataclass
class ResourceDescriptionItem:
    class Config:
        extra = Extra.forbid

    language: TerminologyCode
    purpose: str
    other_details: Dict[str, Any]
    keywords: Optional[List[str]] = None
    use: Optional[str] = None
    misuse: Optional[str] = None
    copyright: Optional[str] = None
    original_resource_uri: Optional[List[Dict[str, Any]]] = None
    _type: Optional[str] = None


@dataclass
class Array:
    _type: Optional[str] = None


class Type107(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid20:
    _type: Type107


class Type108(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name22:
    _type: Optional[Type108] = None


class Type109(Enum):
    PARTY_SELF = "PARTY_SELF"
    PARTY_IDENTIFIED = "PARTY_IDENTIFIED"
    PARTY_RELATED = "PARTY_RELATED"


@dataclass
class Subject3:
    _type: Type109


class Type110(Enum):
    PARTY_SELF = "PARTY_SELF"
    PARTY_IDENTIFIED = "PARTY_IDENTIFIED"
    PARTY_RELATED = "PARTY_RELATED"


@dataclass
class Provider3:
    _type: Type110


class Type111(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class WorkflowId2:
    _type: Optional[Type111] = None


class Type112(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class Protocol2:
    _type: Type112


class Type113(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class GuidelineId2:
    _type: Optional[Type113] = None


class Type114(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class OwnerId4:
    _type: Optional[Type114] = None


@dataclass
class AddressedMessage:
    class Config:
        extra = Extra.forbid

    sender: str
    sender_reference: str
    addressees: Optional[List[str]] = None
    urgency: Optional[int] = None
    message: Optional[Message] = None
    _type: Optional[str] = None


@dataclass
class Uuid:
    class Config:
        extra = Extra.forbid

    value: str
    _type: Optional[str] = None


class Type115(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class ReasonItem:
    _type: Optional[Type115] = None


class Type116(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class OwnerId5:
    _type: Optional[Type116] = None


class Type117(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Function1:
    _type: Optional[Type117] = None


class Type118(Enum):
    PARTY_SELF = "PARTY_SELF"
    PARTY_IDENTIFIED = "PARTY_IDENTIFIED"
    PARTY_RELATED = "PARTY_RELATED"


@dataclass
class Performer:
    _type: Type118


class Type119(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid21:
    _type: Type119


class Type120(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name23:
    _type: Optional[Type120] = None


class Type121(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class Item5:
    _type: Optional[Type121] = None


class Type122(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class Details5:
    _type: Type122


class Type123(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid22:
    _type: Type123


class Type124(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name24:
    _type: Optional[Type124] = None


class Type125(Enum):
    EXTRACT_ENTITY_CHAPTER = "EXTRACT_ENTITY_CHAPTER"
    EXTRACT_CHAPTER = "EXTRACT_CHAPTER"


@dataclass
class Chapter:
    _type: Optional[Type125] = None


@dataclass
class ValidityKind:
    _type: Optional[str] = None


@dataclass
class ObjectVersionId:
    class Config:
        extra = Extra.forbid

    value: str
    _type: Optional[str] = None


@dataclass
class DVInterval:
    class Config:
        extra = Extra.forbid

    lower_unbounded: bool
    upper_unbounded: bool
    lower_included: bool
    upper_included: bool
    lower: Optional[Dict[str, Any]] = None
    upper: Optional[Dict[str, Any]] = None
    _type: Optional[str] = None


class Type126(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid23:
    _type: Type126


class Type127(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name25:
    _type: Optional[Type127] = None


class Type128(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class Details6:
    _type: Type128


class Type129(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Language3:
    _type: Optional[Type129] = None


class Type130(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class OwnerId6:
    _type: Optional[Type130] = None


class Type131(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid24:
    _type: Type131


class Type132(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name26:
    _type: Optional[Type132] = None


@dataclass
class Item6:
    pass


@dataclass
class Date:
    class Config:
        extra = Extra.forbid

    value: Optional[str] = None
    _type: Optional[str] = None


class Type133(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid25:
    _type: Type133


class Type134(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name27:
    _type: Optional[Type134] = None


class Type135(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid26:
    _type: Type135


class Type136(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name28:
    _type: Optional[Type136] = None


class Type137(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class State1:
    _type: Type137


class Type138(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class Data2:
    _type: Type138


class Type139(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Description1:
    _type: Optional[Type139] = None


class Type140(Enum):
    PARTY_SELF = "PARTY_SELF"
    PARTY_IDENTIFIED = "PARTY_IDENTIFIED"
    PARTY_RELATED = "PARTY_RELATED"


@dataclass
class Committer1:
    _type: Type140


class Type141(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Reason:
    _type: Optional[Type141] = None


class Type142(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid27:
    _type: Type142


class Type143(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name29:
    _type: Optional[Type143] = None


class Type144(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class Details7:
    _type: Type144


@dataclass
class DVIdentifier:
    class Config:
        extra = Extra.forbid

    id: str
    issuer: Optional[str] = None
    type: Optional[str] = None
    assigner: Optional[str] = None
    _type: Optional[str] = None


class Type145(Enum):
    DV_EHR_URI = "DV_EHR_URI"
    DV_URI = "DV_URI"


@dataclass
class Hyperlink:
    _type: Optional[Type145] = None


@dataclass
class DateTime:
    class Config:
        extra = Extra.forbid

    value: Optional[str] = None
    _type: Optional[str] = None


class Type146(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid28:
    _type: Type146


class Type147(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name30:
    _type: Optional[Type147] = None


class Type148(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class Details8:
    _type: Type148


class Type149(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Id:
    _type: Type149


@dataclass
class LocatableRef:
    class Config:
        extra = Extra.forbid

    id: Id
    namespace: str
    type: str
    path: Optional[str] = None
    _type: Optional[str] = None


@dataclass
class ListModel:
    _type: Optional[str] = None


class Type150(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid29:
    _type: Type150


class Type151(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name31:
    _type: Optional[Type151] = None


@dataclass
class DVEhrUri:
    class Config:
        extra = Extra.forbid

    value: Optional[str] = None
    _type: Optional[str] = None


@dataclass
class TerminologyTerm:
    class Config:
        extra = Extra.forbid

    text: str
    concept: TerminologyCode
    _type: Optional[str] = None


@dataclass
class ArchetypeId:
    class Config:
        extra = Extra.forbid

    value: str
    _type: Optional[str] = None


class Type152(Enum):
    TERMINOLOGY_ID = "TERMINOLOGY_ID"
    GENERIC_ID = "GENERIC_ID"
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"
    ARCHETYPE_ID = "ARCHETYPE_ID"
    TEMPLATE_ID = "TEMPLATE_ID"


@dataclass
class Id1:
    _type: Type152


@dataclass
class PartyRef:
    class Config:
        extra = Extra.forbid

    id: Id1
    namespace: str
    type: str
    _type: Optional[str] = None


@dataclass
class TemplateId:
    class Config:
        extra = Extra.forbid

    value: str
    _type: Optional[str] = None


class Type153(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid30:
    _type: Type153


class Type154(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name32:
    _type: Optional[Type154] = None


class Type155(Enum):
    PARTY_SELF = "PARTY_SELF"
    PARTY_IDENTIFIED = "PARTY_IDENTIFIED"
    PARTY_RELATED = "PARTY_RELATED"


@dataclass
class Subject4:
    _type: Type155


class Type156(Enum):
    PARTY_SELF = "PARTY_SELF"
    PARTY_IDENTIFIED = "PARTY_IDENTIFIED"
    PARTY_RELATED = "PARTY_RELATED"


@dataclass
class Provider4:
    _type: Type156


class Type157(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class WorkflowId3:
    _type: Optional[Type157] = None


class Type158(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class Data3:
    _type: Type158


@dataclass
class PartyIdentified:
    class Config:
        extra = Extra.forbid

    external_ref: Optional[PartyRef] = None
    name: Optional[str] = None
    identifiers: Optional[List[DVIdentifier]] = Field(None, minItems=1)
    _type: Optional[str] = None


class Type159(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid31:
    _type: Type159


class Type160(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name33:
    _type: Optional[Type160] = None


@dataclass
class Item7:
    pass


class Type161(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid32:
    _type: Type161


class Type162(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name34:
    _type: Optional[Type162] = None


class Type163(Enum):
    PARTY_SELF = "PARTY_SELF"
    PARTY_IDENTIFIED = "PARTY_IDENTIFIED"
    PARTY_RELATED = "PARTY_RELATED"


@dataclass
class Composer:
    _type: Type163


class Type164(Enum):
    INSTRUCTION = "INSTRUCTION"
    EVALUATION = "EVALUATION"
    OBSERVATION = "OBSERVATION"
    ACTION = "ACTION"
    ADMIN_ENTRY = "ADMIN_ENTRY"
    GENERIC_ENTRY = "GENERIC_ENTRY"
    SECTION = "SECTION"


@dataclass
class ContentItem:
    _type: Type164


class Type165(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid33:
    _type: Type165


class Type166(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name35:
    _type: Optional[Type166] = None


class Type167(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class OtherDetails2:
    _type: Type167


class Type168(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Meaning1:
    _type: Optional[Type168] = None


class Type170(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Type169:
    _type: Optional[Type170] = None


@dataclass
class Link:
    class Config:
        extra = Extra.forbid

    meaning: Meaning1
    type: Type169
    target: DVEhrUri
    _type: Optional[str] = None


@dataclass
class TranslationDetails:
    class Config:
        extra = Extra.forbid

    language: TerminologyCode
    author: Dict[str, Any]
    accreditation: Optional[str] = None
    other_details: Optional[Dict[str, Any]] = None
    _type: Optional[str] = None


class Type171(Enum):
    TERMINOLOGY_ID = "TERMINOLOGY_ID"
    GENERIC_ID = "GENERIC_ID"
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"
    ARCHETYPE_ID = "ARCHETYPE_ID"
    TEMPLATE_ID = "TEMPLATE_ID"


@dataclass
class Id2:
    _type: Type171


@dataclass
class AccessGroupRef:
    class Config:
        extra = Extra.forbid

    id: Id2
    namespace: str
    type: str
    _type: Optional[str] = None


class Type172(Enum):
    TERMINOLOGY_ID = "TERMINOLOGY_ID"
    GENERIC_ID = "GENERIC_ID"
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"
    ARCHETYPE_ID = "ARCHETYPE_ID"
    TEMPLATE_ID = "TEMPLATE_ID"


@dataclass
class Id3:
    _type: Type172


@dataclass
class ObjectRef:
    class Config:
        extra = Extra.forbid

    id: Id3
    namespace: str
    type: str
    _type: Optional[str] = None


class Type173(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid34:
    _type: Type173


class Type174(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name36:
    _type: Optional[Type174] = None


@dataclass
class Time:
    class Config:
        extra = Extra.forbid

    value: Optional[str] = None
    _type: Optional[str] = None


class Type175(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class Contribution3:
    _type: Optional[Type175] = None


class Type176(Enum):
    ATTESTATION = "ATTESTATION"
    AUDIT_DETAILS = "AUDIT_DETAILS"


@dataclass
class CommitAudit1:
    _type: Optional[Type176] = None


@dataclass
class DVBoolean:
    class Config:
        extra = Extra.forbid

    value: bool
    _type: Optional[str] = None


@dataclass
class DVUri:
    class Config:
        extra = Extra.forbid

    value: Optional[str] = None
    _type: Optional[str] = None


class Type177(Enum):
    DV_EHR_URI = "DV_EHR_URI"
    DV_URI = "DV_URI"


@dataclass
class Hyperlink1:
    _type: Optional[Type177] = None


class Type178(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid35:
    _type: Type178


class Type179(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name37:
    _type: Optional[Type179] = None


class Type180(Enum):
    PARTY_SELF = "PARTY_SELF"
    PARTY_IDENTIFIED = "PARTY_IDENTIFIED"
    PARTY_RELATED = "PARTY_RELATED"


@dataclass
class Subject5:
    _type: Type180


class Type181(Enum):
    PARTY_SELF = "PARTY_SELF"
    PARTY_IDENTIFIED = "PARTY_IDENTIFIED"
    PARTY_RELATED = "PARTY_RELATED"


@dataclass
class Provider5:
    _type: Type181


class Type182(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class WorkflowId4:
    _type: Optional[Type182] = None


class Type183(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class Protocol3:
    _type: Type183


class Type184(Enum):
    LOCATABLE_REF = "LOCATABLE_REF"
    PARTY_REF = "PARTY_REF"
    ACCESS_GROUP_REF = "ACCESS_GROUP_REF"
    OBJECT_REF = "OBJECT_REF"


@dataclass
class GuidelineId3:
    _type: Optional[Type184] = None


class Type185(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class Description2:
    _type: Type185


class Type186(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid36:
    _type: Type186


class Type187(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name38:
    _type: Optional[Type187] = None


class Type188(Enum):
    EXTRACT_FOLDER = "EXTRACT_FOLDER"
    GENERIC_CONTENT_ITEM = "GENERIC_CONTENT_ITEM"
    OPENEHR_CONTENT_ITEM = "OPENEHR_CONTENT_ITEM"


@dataclass
class Item8:
    _type: Type188


@dataclass
class HierObjectId:
    class Config:
        extra = Extra.forbid

    value: str
    _type: Optional[str] = None


class Type189(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid37:
    _type: Type189


class Type190(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name39:
    _type: Optional[Type190] = None


class Type191(Enum):
    INSTRUCTION = "INSTRUCTION"
    EVALUATION = "EVALUATION"
    OBSERVATION = "OBSERVATION"
    ACTION = "ACTION"
    ADMIN_ENTRY = "ADMIN_ENTRY"
    GENERIC_ENTRY = "GENERIC_ENTRY"
    SECTION = "SECTION"


@dataclass
class Item9:
    _type: Type191


class Type192(Enum):
    OBJECT_VERSION_ID = "OBJECT_VERSION_ID"
    HIER_OBJECT_ID = "HIER_OBJECT_ID"


@dataclass
class Uid38:
    _type: Type192


class Type193(Enum):
    DV_CODED_TEXT = "DV_CODED_TEXT"
    DV_TEXT = "DV_TEXT"


@dataclass
class Name40:
    _type: Optional[Type193] = None


class Type194(Enum):
    ITEM_SINGLE = "ITEM_SINGLE"
    ITEM_TREE = "ITEM_TREE"
    ITEM_LIST = "ITEM_LIST"
    ITEM_TABLE = "ITEM_TABLE"


@dataclass
class Description3:
    _type: Type194


@dataclass
class ExtractManifest:
    class Config:
        extra = Extra.forbid

    entities: Optional[List[ExtractEntityManifest]] = Field(None, minItems=1)
    _type: Optional[str] = None


@dataclass
class RevisionHistoryItem:
    class Config:
        extra = Extra.forbid

    version_id: ObjectVersionId
    audits: List[Audit]
    _type: Optional[str] = None


@dataclass
class DVParsable:
    class Config:
        extra = Extra.forbid

    value: str
    formalism: str
    charset: Optional[CodePhrase] = None
    language: Optional[CodePhrase] = None
    _type: Optional[str] = None


@dataclass
class ExtractVersionSpec:
    class Config:
        extra = Extra.forbid

    include_all_versions: bool
    include_revision_history: bool
    include_data: bool
    commit_time_interval: Optional[DVInterval] = None
    _type: Optional[str] = None


@dataclass
class ResourceDescription:
    class Config:
        extra = Extra.forbid

    original_author: Dict[str, Any]
    lifecycle_state: str
    parent_resource: Dict[str, Any]
    details: List[ResourceDescriptionItem]
    other_contributors: Optional[List[str]] = None
    resource_package_uri: Optional[str] = None
    other_details: Optional[Dict[str, Any]] = None
    _type: Optional[str] = None


@dataclass
class Contribution1:
    class Config:
        extra = Extra.forbid

    uid: HierObjectId
    audit: Audit1
    versions: List[Version]
    _type: Optional[str] = None


@dataclass
class Archetyped:
    class Config:
        extra = Extra.forbid

    archetype_id: ArchetypeId
    rm_version: str
    template_id: Optional[TemplateId] = None
    _type: Optional[str] = None


@dataclass
class InstructionDetails:
    class Config:
        extra = Extra.forbid

    instruction_id: LocatableRef
    activity_id: str
    wf_details: Optional[WfDetails] = None
    _type: Optional[str] = None


@dataclass
class PartySelf:
    class Config:
        extra = Extra.forbid

    external_ref: Optional[PartyRef] = None
    _type: Optional[str] = None


@dataclass
class XContribution:
    class Config:
        extra = Extra.forbid

    uid: HierObjectId
    audit: Audit3
    versions: Optional[List[Version1]] = None
    _type: Optional[str] = None


@dataclass
class ReferenceRange:
    class Config:
        extra = Extra.forbid

    range: DVInterval
    meaning: Meaning
    _type: Optional[str] = None


@dataclass
class DVGeneralTimeSpecification:
    class Config:
        extra = Extra.forbid

    value: DVParsable
    _type: Optional[str] = None


@dataclass
class DVPeriodicTimeSpecification:
    class Config:
        extra = Extra.forbid

    value: DVParsable
    _type: Optional[str] = None


@dataclass
class RevisionHistory:
    class Config:
        extra = Extra.forbid

    items: List[RevisionHistoryItem]
    _type: Optional[str] = None


@dataclass
class DVCount:
    class Config:
        extra = Extra.forbid

    magnitude: int
    normal_status: Optional[CodePhrase] = None
    normal_range: Optional[DVInterval] = None
    other_reference_ranges: Optional[List[ReferenceRange]] = None
    magnitude_status: Optional[str] = None
    accuracy: Optional[float] = None
    accuracy_is_percent: Optional[bool] = None
    _type: Optional[str] = None


@dataclass
class DVDuration:
    class Config:
        extra = Extra.forbid

    value: str
    normal_status: Optional[CodePhrase] = None
    normal_range: Optional[DVInterval] = None
    other_reference_ranges: Optional[List[ReferenceRange]] = Field(None, minItems=1)
    magnitude_status: Optional[str] = None
    accuracy: Optional[float] = None
    accuracy_is_percent: Optional[bool] = None
    _type: Optional[str] = None


@dataclass
class DVProportion:
    class Config:
        extra = Extra.forbid

    numerator: float
    denominator: float
    type: int
    normal_status: Optional[CodePhrase] = None
    normal_range: Optional[DVInterval] = None
    other_reference_ranges: Optional[List[ReferenceRange]] = Field(None, minItems=1)
    magnitude_status: Optional[str] = None
    accuracy: Optional[float] = None
    accuracy_is_percent: Optional[bool] = None
    precision: Optional[int] = None
    _type: Optional[str] = None


@dataclass
class DVQuantity:
    class Config:
        extra = Extra.forbid

    magnitude: float
    units: str
    normal_status: Optional[CodePhrase] = None
    normal_range: Optional[DVInterval] = None
    other_reference_ranges: Optional[List[ReferenceRange]] = None
    magnitude_status: Optional[str] = None
    accuracy: Optional[float] = None
    accuracy_is_percent: Optional[bool] = None
    property: Optional[CodePhrase] = None
    units_system: Optional[str] = None
    units_display_name: Optional[str] = None
    precision: Optional[int] = None
    _type: Optional[str] = None


@dataclass
class DVDate:
    class Config:
        extra = Extra.forbid

    value: str
    normal_status: Optional[CodePhrase] = None
    normal_range: Optional[DVInterval] = None
    other_reference_ranges: Optional[List[ReferenceRange]] = Field(None, minItems=1)
    magnitude_status: Optional[str] = None
    accuracy: Optional[DVDuration] = None
    _type: Optional[str] = None


@dataclass
class DVTime:
    class Config:
        extra = Extra.forbid

    value: str
    normal_status: Optional[CodePhrase] = None
    normal_range: Optional[DVInterval] = None
    other_reference_ranges: Optional[List[ReferenceRange]] = Field(None, minItems=1)
    magnitude_status: Optional[str] = None
    accuracy: Optional[DVDuration] = None
    _type: Optional[str] = None


@dataclass
class DVDateTime:
    class Config:
        extra = Extra.forbid

    value: str
    normal_status: Optional[CodePhrase] = None
    normal_range: Optional[DVInterval] = None
    other_reference_ranges: Optional[List[ReferenceRange]] = Field(None, minItems=1)
    magnitude_status: Optional[str] = None
    accuracy: Optional[DVDuration] = None
    _type: Optional[str] = None


@dataclass
class FeederAuditDetails:
    class Config:
        extra = Extra.forbid

    system_id: str
    location: Optional[Location] = None
    provider: Optional[Provider2] = None
    subject: Optional[Subject2] = None
    time: Optional[DVDateTime] = None
    version_id: Optional[str] = None
    other_details: Optional[OtherDetails] = None
    _type: Optional[str] = None


@dataclass
class FeederAudit:
    class Config:
        extra = Extra.forbid

    originating_system_audit: FeederAuditDetails
    originating_system_item_ids: Optional[List[DVIdentifier]] = None
    feeder_system_item_ids: Optional[List[DVIdentifier]] = None
    original_content: Optional[OriginalContent] = None
    feeder_system_audit: Optional[FeederAuditDetails] = None
    _type: Optional[str] = None


@dataclass
class ItemTree:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name16
    uid: Optional[Uid14] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    items: Optional[List[Item4]] = None
    _type: Optional[str] = None


@dataclass
class History:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name19
    origin: DVDateTime
    uid: Optional[Uid17] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    period: Optional[DVDuration] = None
    duration: Optional[DVDuration] = None
    summary: Optional[Summary] = None
    events: Optional[List[Event]] = Field(None, minItems=1)
    _type: Optional[str] = None


@dataclass
class Folder1:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name23
    uid: Optional[Uid21] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    folders: Optional[List[Folder1]] = None
    items: Optional[List[Item5]] = None
    details: Optional[Details5] = None
    _type: Optional[str] = None


@dataclass
class VersionedObject:
    class Config:
        extra = Extra.forbid

    uid: HierObjectId
    owner_id: OwnerId6
    time_created: DVDateTime
    _type: Optional[str] = None


@dataclass
class Address:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name29
    details: Details7
    uid: Optional[Uid27] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    _type: Optional[str] = None


@dataclass
class PartyRelationship:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name30
    source: PartyRef
    target: PartyRef
    uid: Optional[Uid28] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    details: Optional[Details8] = None
    time_validity: Optional[DVInterval] = None
    _type: Optional[str] = None


@dataclass
class EhrAccess1:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name31
    uid: Optional[Uid29] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    settings: Optional[Dict[str, Any]] = None
    _type: Optional[str] = None


@dataclass
class OpenehrContentItem:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name33
    is_primary: bool
    uid: Optional[Uid31] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    is_changed: Optional[bool] = None
    is_masked: Optional[bool] = None
    item: Optional[Item7] = None
    _type: Optional[str] = None


@dataclass
class EhrStatus1:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name35
    subject: PartySelf
    is_queryable: bool
    is_modifiable: bool
    uid: Optional[Uid33] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    other_details: Optional[OtherDetails2] = None
    _type: Optional[str] = None


@dataclass
class GenericEntry:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name36
    data: ItemTree
    uid: Optional[Uid34] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    _type: Optional[str] = None


@dataclass
class ExtractEntityChapter:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name38
    extract_id_key: str
    uid: Optional[Uid36] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    items: Optional[List[Item8]] = None
    _type: Optional[str] = None


@dataclass
class Section:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name39
    uid: Optional[Uid37] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    items: Optional[List[Item9]] = Field(None, minItems=1)
    _type: Optional[str] = None


@dataclass
class Activity:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name40
    description: Description3
    uid: Optional[Uid38] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    timing: Optional[DVParsable] = None
    action_archetype_id: Optional[str] = None
    _type: Optional[str] = None


@dataclass
class SyncExtractSpec:
    class Config:
        extra = Extra.forbid

    includes_versions: bool
    contribution_list: Optional[List[HierObjectId]] = None
    contributions_since: Optional[DVDateTime] = None
    all_contributions: Optional[bool] = None
    _type: Optional[str] = None


@dataclass
class Ehr:
    class Config:
        extra = Extra.forbid

    system_id: HierObjectId
    ehr_id: HierObjectId
    time_created: DVDateTime
    ehr_access: EhrAccess
    ehr_status: EhrStatus
    contributions: List[Contribution]
    directory: Optional[Directory] = None
    folders: Optional[List[Folder]] = None
    compositions: Optional[List[Composition]] = None
    _type: Optional[str] = None


@dataclass
class PartyIdentity:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name
    details: Details
    uid: Optional[Uid] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    _type: Optional[str] = None


@dataclass
class Cluster:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name1
    items: List[Item]
    uid: Optional[Uid1] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    _type: Optional[str] = None


@dataclass
class ExtractFolder:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name2
    uid: Optional[Uid2] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    items: Optional[List[Item1]] = None
    _type: Optional[str] = None


@dataclass
class ExtractChapter:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name4
    uid: Optional[Uid4] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    items: Optional[List[Item2]] = None
    _type: Optional[str] = None


@dataclass
class Capability:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name7
    credentials: Credentials
    uid: Optional[Uid7] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    time_validity: Optional[DVInterval] = None
    _type: Optional[str] = None


@dataclass
class PointEvent:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name8
    time: DVDateTime
    data: Data1
    uid: Optional[Uid8] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    state: Optional[State] = None
    _type: Optional[str] = None


@dataclass
class SyncExtract:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name11
    specification: SyncExtractSpec
    uid: Optional[Uid10] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    items: Optional[List[XContribution]] = None
    _type: Optional[str] = None


@dataclass
class SyncExtractRequest:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name20
    specification: SyncExtractSpec
    uid: Optional[Uid18] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    _type: Optional[str] = None


@dataclass
class Contact:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name21
    uid: Optional[Uid19] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    time_validity: Optional[DVInterval] = None
    addresses: Optional[List[Address]] = Field(None, minItems=1)
    _type: Optional[str] = None


@dataclass
class Organisation:
    class Config:
        extra = Extra.forbid

    uid: Uid23
    archetype_node_id: str
    name: Name25
    identities: List[PartyIdentity]
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    details: Optional[Details6] = None
    contacts: Optional[List[Contact]] = Field(None, minItems=1)
    relationships: Optional[List[PartyRelationship]] = Field(None, minItems=1)
    reverse_relationships: Optional[List[LocatableRef]] = Field(None, minItems=1)
    roles: Optional[List[PartyRef]] = Field(None, minItems=1)
    languages: Optional[List[Language3]] = Field(None, minItems=1)
    _type: Optional[str] = None


@dataclass
class ItemTable:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name27
    uid: Optional[Uid25] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    rows: Optional[List[Cluster]] = None
    _type: Optional[str] = None


@dataclass
class Person:
    class Config:
        extra = Extra.forbid

    uid: Uid5
    archetype_node_id: str
    name: Name5
    identities: List[PartyIdentity]
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    details: Optional[Details1] = None
    contacts: Optional[List[Contact]] = Field(None, minItems=1)
    relationships: Optional[List[PartyRelationship]] = Field(None, minItems=1)
    reverse_relationships: Optional[List[LocatableRef]] = Field(None, minItems=1)
    roles: Optional[List[PartyRef]] = Field(None, minItems=1)
    languages: Optional[List[Language]] = Field(None, minItems=1)
    _type: Optional[str] = None


@dataclass
class Role:
    class Config:
        extra = Extra.forbid

    uid: Uid11
    archetype_node_id: str
    name: Name12
    identities: List[PartyIdentity]
    performer: PartyRef
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    details: Optional[Details2] = None
    contacts: Optional[List[Contact]] = Field(None, minItems=1)
    relationships: Optional[List[PartyRelationship]] = Field(None, minItems=1)
    reverse_relationships: Optional[List[LocatableRef]] = Field(None, minItems=1)
    capabilities: Optional[List[Capability]] = Field(None, minItems=1)
    time_validity: Optional[DVInterval] = None
    _type: Optional[str] = None


@dataclass
class Agent:
    class Config:
        extra = Extra.forbid

    uid: Uid12
    archetype_node_id: str
    name: Name13
    identities: List[PartyIdentity]
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    details: Optional[Details3] = None
    contacts: Optional[List[Contact]] = Field(None, minItems=1)
    relationships: Optional[List[PartyRelationship]] = Field(None, minItems=1)
    reverse_relationships: Optional[List[LocatableRef]] = Field(None, minItems=1)
    roles: Optional[List[PartyRef]] = Field(None, minItems=1)
    languages: Optional[List[Language1]] = Field(None, minItems=1)
    _type: Optional[str] = None


@dataclass
class Group:
    class Config:
        extra = Extra.forbid

    uid: Uid13
    archetype_node_id: str
    name: Name14
    identities: List[PartyIdentity]
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    details: Optional[Details4] = None
    contacts: Optional[List[Contact]] = Field(None, minItems=1)
    relationships: Optional[List[PartyRelationship]] = Field(None, minItems=1)
    reverse_relationships: Optional[List[LocatableRef]] = Field(None, minItems=1)
    roles: Optional[List[PartyRef]] = Field(None, minItems=1)
    languages: Optional[List[Language2]] = Field(None, minItems=1)
    _type: Optional[str] = None


@dataclass
class AuditDetails:
    class Config:
        extra = Extra.forbid

    system_id: str
    time_committed: DVDateTime
    change_type: DVCodedText
    committer: Committer
    description: Optional[Description] = None
    _type: Optional[str] = None


@dataclass
class ExtractParticipation:
    class Config:
        extra = Extra.forbid

    performer: str
    function: Function
    mode: Optional[DVCodedText] = None
    time: Optional[DVInterval] = None
    _type: Optional[str] = None


@dataclass
class PartyRelated:
    class Config:
        extra = Extra.forbid

    relationship: DVCodedText
    external_ref: Optional[PartyRef] = None
    name: Optional[str] = None
    identifiers: Optional[List[DVIdentifier]] = Field(None, minItems=1)
    _type: Optional[str] = None


@dataclass
class Instruction:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name3
    language: CodePhrase
    encoding: CodePhrase
    subject: Subject
    narrative: Narrative
    uid: Optional[Uid3] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    provider: Optional[Provider] = None
    other_participations: Optional[List[Participation]] = None
    workflow_id: Optional[WorkflowId] = None
    protocol: Optional[Protocol] = None
    guideline_id: Optional[GuidelineId] = None
    expiry_time: Optional[DVDateTime] = None
    wf_definition: Optional[DVParsable] = None
    activities: Optional[List[Activity]] = Field(None, minItems=1)
    _type: Optional[str] = None


@dataclass
class Evaluation:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name6
    language: CodePhrase
    encoding: CodePhrase
    subject: Subject1
    data: Data
    uid: Optional[Uid6] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    provider: Optional[Provider1] = None
    other_participations: Optional[List[Participation]] = None
    workflow_id: Optional[WorkflowId1] = None
    protocol: Optional[Protocol1] = None
    guideline_id: Optional[GuidelineId1] = None
    _type: Optional[str] = None


@dataclass
class OriginalVersion:
    class Config:
        extra = Extra.forbid

    contribution: Contribution2
    commit_audit: CommitAudit
    uid: ObjectVersionId
    lifecycle_state: DVCodedText
    signature: Optional[str] = None
    preceding_version_uid: Optional[ObjectVersionId] = None
    other_input_version_uids: Optional[List[ObjectVersionId]] = Field(None, minItems=1)
    attestations: Optional[List[Attestation]] = Field(None, minItems=1)
    data: Optional[Dict[str, Any]] = None
    _type: Optional[str] = None


@dataclass
class XVersionedParty:
    class Config:
        extra = Extra.forbid

    uid: HierObjectId
    owner_id: OwnerId
    time_created: DVDateTime
    total_version_count: int
    extract_version_count: int
    revision_history: Optional[RevisionHistory] = None
    versions: Optional[List[OriginalVersion]] = None
    _type: Optional[str] = None


@dataclass
class ExtractRequest:
    class Config:
        extra = Extra.forbid

    uid: HierObjectId
    archetype_node_id: str
    name: Name9
    extract_spec: ExtractSpec
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    update_spec: Optional[ExtractUpdateSpec] = None
    _type: Optional[str] = None


@dataclass
class EventContext:
    class Config:
        extra = Extra.forbid

    start_time: DVDateTime
    setting: DVCodedText
    health_care_facility: Optional[HealthCareFacility] = None
    end_time: Optional[DVDateTime] = None
    participations: Optional[List[Participation]] = Field(None, minItems=1)
    location: Optional[str] = None
    other_context: Optional[OtherContext] = None
    _type: Optional[str] = None


@dataclass
class ItemSingle:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name10
    item: Element
    uid: Optional[Uid9] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    _type: Optional[str] = None


@dataclass
class XVersionedComposition:
    class Config:
        extra = Extra.forbid

    uid: HierObjectId
    owner_id: OwnerId1
    time_created: DVDateTime
    total_version_count: int
    extract_version_count: int
    revision_history: Optional[RevisionHistory] = None
    versions: Optional[List[OriginalVersion]] = None
    _type: Optional[str] = None


@dataclass
class XVersionedFolder:
    class Config:
        extra = Extra.forbid

    uid: HierObjectId
    owner_id: OwnerId2
    time_created: DVDateTime
    total_version_count: int
    extract_version_count: int
    revision_history: Optional[RevisionHistory] = None
    versions: Optional[List[OriginalVersion]] = None
    _type: Optional[str] = None


@dataclass
class DVOrdinal:
    class Config:
        extra = Extra.forbid

    value: int
    symbol: DVCodedText
    normal_status: Optional[CodePhrase] = None
    normal_range: Optional[DVInterval] = None
    other_reference_ranges: Optional[List[ReferenceRange]] = Field(None, minItems=1)
    _type: Optional[str] = None


@dataclass
class ExtractActionRequest:
    class Config:
        extra = Extra.forbid

    uid: HierObjectId
    archetype_node_id: str
    name: Name15
    request_id: RequestId
    action: DVCodedText
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    _type: Optional[str] = None


@dataclass
class XVersionedEhrAccess:
    class Config:
        extra = Extra.forbid

    uid: HierObjectId
    owner_id: OwnerId3
    time_created: DVDateTime
    total_version_count: int
    extract_version_count: int
    revision_history: Optional[RevisionHistory] = None
    versions: Optional[List[OriginalVersion]] = None
    _type: Optional[str] = None


@dataclass
class Element:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name17
    uid: Optional[Uid15] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    null_flavour: Optional[DVCodedText] = None
    value: Optional[Value] = None
    null_reason: Optional[NullReason] = None
    _type: Optional[str] = None


@dataclass
class ExtractSpec:
    class Config:
        extra = Extra.forbid

    extract_type: DVCodedText
    include_multimedia: bool
    priority: int
    link_depth: int
    manifest: ExtractManifest
    criteria: Optional[List[DVParsable]] = None
    version_spec: Optional[ExtractVersionSpec] = None
    other_details: Optional[OtherDetails1] = None
    _type: Optional[str] = None


@dataclass
class DVState:
    class Config:
        extra = Extra.forbid

    value: DVCodedText
    is_terminal: bool
    _type: Optional[str] = None


@dataclass
class ItemList:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name18
    uid: Optional[Uid16] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    items: Optional[List[Element]] = None
    _type: Optional[str] = None


@dataclass
class TermMapping:
    class Config:
        extra = Extra.forbid

    match: str
    target: CodePhrase
    purpose: Optional[DVCodedText] = None
    _type: Optional[str] = None


@dataclass
class ExtractUpdateSpec:
    class Config:
        extra = Extra.forbid

    persist_in_server: bool
    update_method: CodePhrase
    trigger_events: Optional[List[DVCodedText]] = Field(None, minItems=1)
    repeat_period: Optional[DVDuration] = None
    _type: Optional[str] = None


@dataclass
class Observation:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name22
    language: CodePhrase
    encoding: CodePhrase
    subject: Subject3
    data: History
    uid: Optional[Uid20] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    provider: Optional[Provider3] = None
    other_participations: Optional[List[Participation]] = None
    workflow_id: Optional[WorkflowId2] = None
    protocol: Optional[Protocol2] = None
    guideline_id: Optional[GuidelineId2] = None
    state: Optional[History] = None
    _type: Optional[str] = None


@dataclass
class XVersionedObject:
    class Config:
        extra = Extra.forbid

    uid: HierObjectId
    owner_id: OwnerId4
    time_created: DVDateTime
    total_version_count: int
    extract_version_count: int
    revision_history: Optional[RevisionHistory] = None
    versions: Optional[List[OriginalVersion]] = None
    _type: Optional[str] = None


@dataclass
class IsmTransition:
    class Config:
        extra = Extra.forbid

    current_state: DVCodedText
    transition: Optional[DVCodedText] = None
    careflow_step: Optional[DVCodedText] = None
    reason: Optional[List[ReasonItem]] = None
    _type: Optional[str] = None


@dataclass
class XVersionedEhrStatus:
    class Config:
        extra = Extra.forbid

    uid: HierObjectId
    owner_id: OwnerId5
    time_created: DVDateTime
    total_version_count: int
    extract_version_count: int
    revision_history: Optional[RevisionHistory] = None
    versions: Optional[List[OriginalVersion]] = None
    _type: Optional[str] = None


@dataclass
class Participation:
    class Config:
        extra = Extra.forbid

    function: Function1
    performer: Performer
    time: Optional[DVInterval] = None
    mode: Optional[DVCodedText] = None
    _type: Optional[str] = None


@dataclass
class Extract:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name24
    time_created: DVDateTime
    system_id: HierObjectId
    sequence_nr: int
    uid: Optional[Uid22] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    request_id: Optional[HierObjectId] = None
    specification: Optional[ExtractSpec] = None
    chapters: Optional[List[Chapter]] = None
    participations: Optional[List[ExtractParticipation]] = None
    _type: Optional[str] = None


@dataclass
class GenericContentItem:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name26
    is_primary: bool
    uid: Optional[Uid24] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    is_changed: Optional[bool] = None
    is_masked: Optional[bool] = None
    item: Optional[Item6] = None
    item_type: Optional[DVCodedText] = None
    item_type_version: Optional[str] = None
    author: Optional[str] = None
    creation_time: Optional[datetime] = None
    authoriser: Optional[str] = None
    authorisation_time: Optional[datetime] = None
    item_status: Optional[DVCodedText] = None
    version_id: Optional[str] = None
    version_set_id: Optional[str] = None
    system_id: Optional[str] = None
    other_details: Optional[List[str]] = None
    _type: Optional[str] = None


@dataclass
class IntervalEvent:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name28
    time: DVDateTime
    data: Data2
    width: DVDuration
    math_function: DVCodedText
    uid: Optional[Uid26] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    state: Optional[State1] = None
    sample_count: Optional[int] = None
    _type: Optional[str] = None


@dataclass
class Attestation:
    class Config:
        extra = Extra.forbid

    system_id: str
    time_committed: DVDateTime
    change_type: DVCodedText
    committer: Committer1
    reason: Reason
    is_pending: bool
    description: Optional[Description1] = None
    attested_view: Optional[DVMultimedia] = None
    proof: Optional[str] = None
    items: Optional[List[DVEhrUri]] = None
    _type: Optional[str] = None


@dataclass
class DVCodedText:
    class Config:
        extra = Extra.forbid

    value: str
    defining_code: CodePhrase
    hyperlink: Optional[Hyperlink] = None
    language: Optional[CodePhrase] = None
    encoding: Optional[CodePhrase] = None
    formatting: Optional[str] = None
    mappings: Optional[List[TermMapping]] = Field(None, minItems=1)
    _type: Optional[str] = None


@dataclass
class DVScale:
    class Config:
        extra = Extra.forbid

    value: float
    symbol: DVCodedText
    normal_status: Optional[CodePhrase] = None
    normal_range: Optional[DVInterval] = None
    other_reference_ranges: Optional[List[ReferenceRange]] = Field(None, minItems=1)
    _type: Optional[str] = None


@dataclass
class AdminEntry:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name32
    language: CodePhrase
    encoding: CodePhrase
    subject: Subject4
    data: Data3
    uid: Optional[Uid30] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    provider: Optional[Provider4] = None
    other_participations: Optional[List[Participation]] = None
    workflow_id: Optional[WorkflowId3] = None
    _type: Optional[str] = None


@dataclass
class Composition1:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name34
    language: CodePhrase
    territory: CodePhrase
    category: DVCodedText
    composer: Composer
    uid: Optional[Uid32] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    context: Optional[EventContext] = None
    content: Optional[List[ContentItem]] = Field(None, minItems=1)
    _type: Optional[str] = None


@dataclass
class ImportedVersion:
    class Config:
        extra = Extra.forbid

    contribution: Contribution3
    commit_audit: CommitAudit1
    item: OriginalVersion
    signature: Optional[str] = None
    _type: Optional[str] = None


@dataclass
class DVText:
    class Config:
        extra = Extra.forbid

    value: str
    hyperlink: Optional[Hyperlink1] = None
    language: Optional[CodePhrase] = None
    encoding: Optional[CodePhrase] = None
    formatting: Optional[str] = None
    mappings: Optional[List[TermMapping]] = Field(None, minItems=1)
    _type: Optional[str] = None


@dataclass
class Action:
    class Config:
        extra = Extra.forbid

    archetype_node_id: str
    name: Name37
    language: CodePhrase
    encoding: CodePhrase
    subject: Subject5
    time: DVDateTime
    description: Description2
    ism_transition: IsmTransition
    uid: Optional[Uid35] = None
    archetype_details: Optional[Archetyped] = None
    feeder_audit: Optional[FeederAudit] = None
    links: Optional[List[Link]] = Field(None, minItems=1)
    provider: Optional[Provider5] = None
    other_participations: Optional[List[Participation]] = None
    workflow_id: Optional[WorkflowId4] = None
    protocol: Optional[Protocol3] = None
    guideline_id: Optional[GuidelineId3] = None
    instruction_details: Optional[InstructionDetails] = None
    _type: Optional[str] = None
