  name: CI

  on:
    push:
      branches: [ master, develop ]
    pull_request:
      branches: [ master, develop ]

  jobs:
    test:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [ "3.8", "3.9", "3.10"]

      steps:
      - name: workaround
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - uses: actions/checkout@v3.0.1
        with:
          fetch-depth: '0'

      - uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'


      - name: Install poetry
        uses: Gr1N/setup-poetry@v7
        # with:
        #   virtualenvs-create: true
        #   virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: poetry-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: install
        run: make install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: test
        run: poetry run make test

    badges:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [ "3.8" ]
      if: github.event_name == 'push'
      needs: test

      steps:
        - name: workaround
          run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

        - uses: actions/checkout@v3.0.1
          with:
            fetch-depth: '0'

        - uses: actions/setup-python@v2
          with:
            python-version: '${{ matrix.python-version }}'

        - name: Install poetry
          uses: Gr1N/setup-poetry@v7
          # with:
          #   virtualenvs-create: true
          #   virtualenvs-in-project: true

        - name: Load cached venv
          id: cached-poetry-dependencies
          uses: actions/cache@v2
          with:
            path: ~/.cache/pypoetry/virtualenvs
            key: poetry-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

        - name: badges
          run: poetry run make clean badges

        - name: commit reports and badges
          uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
          with:
            add: docs/reports

    #from https://mestrak.com/blog/semantic-release-with-python-poetry-github-actions-20nn
    release:
      needs: test
      if: github.event_name == 'push' && github.ref == 'refs/heads/master' && !contains(github.event.head_commit.message, 'chore(release):')
      runs-on: ubuntu-latest
      steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/checkout@v3.0.1
        with:
          fetch-depth: '0'
      - name: publish release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # - name: publish prerelease
      #   if: github.event_name == 'pull_request' && github.base_ref == 'master'
      #   uses: relekang/python-semantic-release@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     additional_options: --prerelease
