  name: CI

  on:
    push:
      branches: [ master, develop, test/test_ci ]
    pull_request:
      branches: [ master, develop ]

  jobs:
    test:
      runs-on: ubuntu-latest
      env:
        POETRY_VIRTUALENVS_CREATE: false

      steps:
      - name: workaround
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"


      - uses: actions/checkout@v3.0.1
        with:
          fetch-depth: '0'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8' 

      - name: install deps
        run: pip install poetry

      - name: install
        run: make install

      - name: test
        run: make test

      - name: gen badges
        run: make badges

      - name: commit reports and badges
        if: github.event_name == 'push'
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: 'reports'

    #from https://mestrak.com/blog/semantic-release-with-python-poetry-github-actions-20nn
    release:
      needs: test
      # https://github.community/t/how-do-i-specify-job-dependency-running-in-another-workflow/16482
      if: github.event_name == 'push' && github.ref == 'refs/heads/master' && !contains(github.event.head_commit.message, 'chore(release):')
      runs-on: ubuntu-latest
      steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/checkout@v3.0.1
        with:
          fetch-depth: '0'
      - name: Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
